PREFIX csf: <https://example.org/nist-csf-2.0/concept/>
PREFIX csfref: <https://example.org/nist-csf-2.0/reference/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?functionNotation ?functionLabel ?functionDefinition ?categoryNotation ?categoryLabel ?categoryDefinition
WHERE {
  csf:GV skos:notation ?functionNotation ;
         skos:prefLabel ?functionLabel ;
         skos:definition ?functionDefinition .
  FILTER(LANGMATCHES(LANG(?functionLabel), "en"))
  FILTER(LANGMATCHES(LANG(?functionDefinition), "en"))

  VALUES ?category { csf:GV-PO csf:GV-OV }
  ?category skos:broader csf:GV ;
            skos:notation ?categoryNotation ;
            skos:prefLabel ?categoryLabel ;
            skos:definition ?categoryDefinition .
  FILTER(LANGMATCHES(LANG(?categoryLabel), "en"))
  FILTER(LANGMATCHES(LANG(?categoryDefinition), "en"))
}
ORDER BY ?categoryNotation
