PREFIX csf: <https://w3id.org/nist-csf2-skos/concept/>
PREFIX csfref: <https://w3id.org/nist-csf2-skos/reference/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?notation ?label ?definition
WHERE {
  VALUES ?concept { csf:PR-AA-01 csf:PR-AA-02 csf:PR-AA-03 csf:PR-AA-04 csf:PR-AA-05 csf:DE-CM-03 }
  ?concept skos:notation ?notation ;
           skos:prefLabel ?label ;
           skos:definition ?definition .
  FILTER(LANGMATCHES(LANG(?label), "en"))
  FILTER(LANGMATCHES(LANG(?definition), "en"))
}
ORDER BY ?notation
