PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT ?isoConcept ?reference ?nistConcept ?nistNotation ?nistLabel
WHERE {
  ?reference skos:exactMatch ?isoConcept .
  ?nistConcept dcterms:references ?reference ;
               skos:notation ?nistNotation ;
               skos:prefLabel ?nistLabel .

  FILTER(lang(?nistLabel) = "en")
  FILTER(STRSTARTS(STR(?isoConcept), "https://wiren301.github.io/iso27001-skos-taxonomy/"))
}
ORDER BY ?isoConcept ?nistNotation
LIMIT 50
